force-app/main/default/objects/Payload_Operation__mdt/Payload_Operation__mdt.object-meta.xml
<CustomObject>
    <label>Payload Operation</label>
    <pluralLabel>Payload Operations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Payload_Operation__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payload_Operation__mdt/fields/HTTP_Method__c.field-meta.xml
<CustomField>
    <fullName>HTTP_Method__c</fullName>
    <label>HTTP Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payload_Operation__mdt/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <description>parameters in url</description>
    <label>Params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PayloadTransaction.cls
/**
* @File Name:	PayloadTransaction.cls
* @Description: Manages HTTP REST API Callouts
* @Author:   	Fan Yang
* @Group:   	Apex
* @Last Modified by:   Yutian Zheng
* @Last Modified time: 2019-12-08
* @Modification Log	:
*-------------------------------------------------------------------------------------
* Ver       Date        Author      Modification
* 1.0       2019-04-03  Fan Yang    Created the file/class
* 2.0       2019-12-08  Yutian      Refactor
*/
global inherited sharing class PayloadTransaction
{
    public String endPoint;
    public String httpMethod;
    public String requestBody;
    public HttpRequest request = new HttpRequest();
    public HTTPResponse response = new HTTPResponse();
    public Exception err;
    public Long startTimeMilliseconds;
    public Long endTimeMilliseconds;
    public Integer  requestTimeout;
    public Boolean hasException { get { return null != this.err; } }
    public String  textResponse { get { return
        this.hasException ? 'Error: ' + this.err.getMessage() : this.response.getBody();
    }}

    public PayloadTransaction(Payload_Operation__mdt op){
        this.startTimeMilliseconds = System.currentTimeMillis();
        this.endPoint = formEndPoint(op);        
        this.httpMethod = op.HTTP_Method__c;
        this.request = formHTTPRequest();
    }

    private String formEndPoint(Payload_Operation__mdt op){
        String endPoint = op.Endpoint__c;
        if(endPoint.contains('{id}') && String.isNotEmpty(op.Params__c)){
            endPoint = endPoint.replace('{id}', op.Params__c);
        }
        return endPoint;
    }

    private HTTPRequest formHTTPRequest() {
        //addHeaderParameters();
        HTTPRequest request = new HTTPRequest();
        if(String.isNotEmpty(endPoint)) {
            request.setEndpoint(endPoint);
        }
        if(String.isNotEmpty(httpMethod)) {
            request.setMethod(httpMethod);
        }
        if(String.isNotEmpty(requestBody)) {
            request.setBody(requestBody);
        }
        if(requestTimeout!=null) {
            request.setTimeout(requestTimeout);
        }
        return request;
    }


    public Exception getError(){
        return this.err;
    }

    //fanxyang 040318
    public void addError(Exception e){
        this.err = e;
    }

    public PayloadTransaction(){}

        /**
    * @author Fan Yang
    * @date 4/4/2018
    * @description Persist log to Salesforce
    */
    public PayloadTransaction saveLog(){
        PayloadLog.createSystemLog(
            new PayloadLog(this.request, this.response, this.err, this.startTimeMilliseconds, this.endTimeMilliseconds)
        );//dml 
        return this;
    }

}